// wordChoices.js - Distractor words for the "Choose the Right Word" mode
var WordChoices = (function () {
  // For each word, 10 distractors:
  // - Similar sounding (rhymes, shared phonemes, minimal pairs)
  // - Related or confusing words
  // - Similar looking (spelling)
  var CHOICES = {
    "action": ["auction", "fashion", "fraction", "station", "caption", "motion", "option", "traction", "section", "addition"],
    "add": ["odd", "aid", "bad", "dad", "had", "and", "sad", "end", "mad", "ads"],
    "advice": ["advise", "device", "practice", "notice", "office", "price", "twice", "dice", "nice", "voice"],
    "after": ["laughter", "faster", "master", "chapter", "actor", "alter", "offer", "other", "aster", "before"],
    "all": ["ball", "call", "fall", "hall", "mall", "tall", "wall", "owl", "ill", "ale"],
    "almost": ["also", "always", "already", "alone", "along", "although", "almond", "mostly", "utmost", "about"],
    "always": ["hallways", "also", "almost", "already", "away", "walkways", "alleys", "airways", "sideways", "anyways"],
    "amount": ["account", "about", "around", "amaze", "among", "aloud", "announce", "mount", "count", "fountain"],
    "back": ["pack", "black", "track", "rack", "stack", "snack", "sack", "lack", "crack", "bark"],
    "bake": ["make", "cake", "lake", "take", "fake", "wake", "sake", "brake", "shake", "rake"],
    "banner": ["manner", "dinner", "runner", "batter", "butter", "hammer", "planner", "scanner", "tanner", "winner"],
    "baseball": ["basketball", "football", "baseball", "handball", "snowball", "fireball", "meatball", "eyeball", "pinball", "softball"],
    "basket": ["blanket", "biscuit", "bucket", "bracket", "casket", "cricket", "jacket", "ticket", "rocket", "pocket"],
    "bear": ["beer", "bare", "dear", "fear", "gear", "hear", "near", "pear", "tear", "wear"],
    "behind": ["begin", "remind", "beside", "between", "beyond", "below", "beneath", "before", "believe", "belong"],
    "bell": ["ball", "bill", "belt", "bull", "fell", "tell", "well", "yell", "sell", "spell"],
    "belt": ["bell", "best", "bolt", "built", "felt", "melt", "bent", "boat", "blast", "ballet"],
    "best": ["rest", "test", "nest", "west", "pest", "chest", "quest", "beast", "blast", "belt"],
    "bike": ["like", "hike", "bite", "kite", "pike", "strike", "mike", "spike", "bake", "back"],
    "blouse": ["house", "mouse", "browse", "grouse", "louse", "spouse", "bruise", "blues", "blooms", "blocks"],
    "boat": ["coat", "goat", "moat", "float", "note", "boot", "bolt", "bone", "beat", "bat"],
    "book": ["look", "cook", "hook", "took", "brook", "nook", "shook", "boot", "back", "brick"],
    "boots": ["books", "roots", "hoots", "suits", "boats", "bolts", "boost", "toots", "shoots", "fruits"],
    "boring": ["roaring", "pouring", "snoring", "scoring", "soaring", "storing", "morning", "flooring", "adoring", "ignoring"],
    "bow": ["row", "low", "cow", "how", "now", "show", "slow", "grow", "flow", "snow"],
    "box": ["fox", "socks", "blocks", "rocks", "locks", "clocks", "docks", "knocks", "stocks", "talks"],
    "brave": ["cave", "gave", "save", "wave", "grave", "shave", "pave", "crave", "brake", "blame"],
    "brush": ["crush", "rush", "blush", "flush", "hush", "gush", "mush", "bush", "crash", "fresh"],
    "buckle": ["bubble", "bundle", "butter", "puzzle", "muscle", "muddle", "chuckle", "knuckle", "couple", "uncle"],
    "bunny": ["funny", "sunny", "honey", "money", "tummy", "buddy", "dummy", "puppy", "penny", "busy"],
    "cake": ["bake", "lake", "make", "take", "fake", "wake", "shake", "flake", "stake", "snake"],
    "camera": ["banana", "canada", "candle", "cancel", "capture", "chapter", "cobra", "comma", "camper", "corner"],
    "cannot": ["carrot", "cabin", "camel", "captain", "carpet", "channel", "parrot", "cannon", "canoe", "canvas"],
    "care": ["car", "dare", "fair", "hair", "pair", "rare", "share", "stare", "bear", "wear"],
    "castle": ["cattle", "cancel", "candle", "cradle", "kettle", "bottle", "rattle", "little", "hassle", "fossil"],
    "catch": ["match", "batch", "patch", "watch", "scratch", "hatch", "latch", "snatch", "attach", "cash"],
    "caught": ["taught", "bought", "brought", "fought", "thought", "cough", "court", "count", "cause", "called"],
    "chased": ["changed", "charged", "checked", "chased", "cheered", "chopped", "clashed", "crashed", "erased", "traced"],
    "chew": ["shoe", "few", "new", "drew", "flew", "grew", "blew", "clue", "glue", "true"],
    "child": ["mild", "wild", "build", "chill", "chain", "change", "chance", "chalk", "chief", "climb"],
    "children": ["chicken", "kitchen", "kitten", "mittens", "golden", "hidden", "garden", "hundred", "listen", "frozen"],
    "choke": ["joke", "broke", "spoke", "smoke", "stroke", "woke", "poke", "cloak", "check", "chalk"],
    "cinema": ["camera", "center", "cereal", "circle", "chicken", "chimney", "china", "dinner", "cinnamon", "mineral"],
    "city": ["kitty", "pretty", "fifty", "pity", "witty", "gritty", "dizzy", "silly", "busy", "easy"],
    "climb": ["lime", "time", "dime", "mime", "crime", "prime", "slime", "chime", "claim", "clamp"],
    "cloudy": ["loudly", "proudly", "clouded", "crowded", "county", "clumsy", "grouchy", "rowdy", "muddy", "stormy"],
    "clown": ["crown", "brown", "down", "frown", "gown", "town", "grown", "drown", "cloud", "clean"],
    "coat": ["boat", "goat", "moat", "float", "note", "cold", "coal", "coast", "cost", "cart"],
    "coffee": ["toffee", "coughing", "copy", "cozy", "cookie", "copper", "corner", "cottage", "couple", "cougar"],
    "cold": ["bold", "fold", "gold", "hold", "mold", "old", "sold", "told", "coal", "cord"],
    "come": ["some", "home", "dome", "comb", "calm", "game", "gum", "hum", "rum", "sum"],
    "computer": ["commuter", "container", "cucumber", "customer", "carpenter", "chapter", "counter", "monster", "rooster", "scooter"],
    "cookies": ["rookies", "bookies", "goodies", "hoodies", "coolers", "noodles", "hookers", "cooking", "looking", "brookies"],
    "corn": ["born", "horn", "torn", "worn", "cork", "cord", "core", "coin", "cone", "corner"],
    "couch": ["coach", "pouch", "touch", "grouch", "crouch", "ouch", "couch", "catch", "church", "count"],
    "cracker": ["tracker", "stacker", "hacker", "packer", "cracker", "rocker", "locker", "sucker", "checker", "flicker"],
    "cubs": ["cups", "cuts", "clubs", "cabs", "curbs", "pubs", "rubs", "tubs", "bugs", "hugs"],
    "cup": ["cut", "cub", "cap", "cop", "pup", "sup", "up", "luck", "duck", "tuck"],
    "daily": ["daisy", "dairy", "dainty", "fairly", "mainly", "rarely", "really", "early", "easily", "family"],
    "doll": ["ball", "call", "tall", "fall", "hall", "wall", "roll", "bell", "dull", "dill"],
    "dream": ["cream", "stream", "scream", "gleam", "steam", "beam", "team", "seam", "drum", "drama"],
    "dress": ["press", "stress", "bless", "mess", "guess", "less", "rest", "fresh", "grass", "cross"],
    "drive": ["dive", "five", "hive", "live", "thrive", "strive", "arrive", "alive", "driver", "driven"],
    "drove": ["stove", "grove", "dove", "wove", "cove", "clove", "prove", "move", "drove", "above"],
    "dryer": ["drier", "flyer", "fryer", "buyer", "player", "prayer", "layer", "mayor", "driver", "dinner"],
    "duck": ["luck", "truck", "stuck", "buck", "chuck", "muck", "tuck", "cluck", "pluck", "dock"],
    "egg": ["leg", "beg", "peg", "edge", "age", "big", "bag", "bug", "end", "add"],
    "eight": ["ate", "gate", "late", "mate", "plate", "great", "weight", "wait", "fight", "light"],
    "elevator": ["alligator", "escalator", "illustrator", "evaporator", "elaborate", "celebrate", "moderator", "generator", "decorator", "operator"],
    "eleven": ["elephant", "elegant", "element", "electric", "elbow", "envelope", "heaven", "seven", "lemon", "melon"],
    "face": ["place", "race", "space", "trace", "grace", "pace", "base", "case", "lace", "fake"],
    "find": ["kind", "mind", "wind", "blind", "grind", "behind", "bind", "lined", "dined", "fine"],
    "fire": ["hire", "tire", "wire", "desire", "admire", "entire", "retire", "require", "five", "fine"],
    "five": ["dive", "drive", "hive", "live", "thrive", "arrive", "alive", "jive", "fire", "fine"],
    "flour": ["flower", "floor", "four", "hour", "our", "power", "tower", "shower", "sour", "flavor"],
    "foggy": ["froggy", "soggy", "boggy", "doggy", "foggy", "groggy", "muddy", "fuzzy", "lucky", "funny"],
    "football": ["baseball", "basketball", "softball", "handball", "footwear", "footprint", "doorbell", "fireball", "snowball", "eyeball"],
    "fork": ["cork", "pork", "work", "stork", "york", "park", "bark", "dark", "mark", "farm"],
    "fur": ["sir", "her", "blur", "stir", "purr", "burr", "spur", "were", "sure", "four"],
    "fuzzy": ["funny", "furry", "fussy", "dizzy", "busy", "fizzy", "jazzy", "muddy", "puppy", "foggy"],
    "garage": ["garbage", "garden", "courage", "luggage", "manage", "message", "package", "passage", "storage", "village"],
    "gift": ["lift", "drift", "shift", "swift", "gist", "grit", "grip", "give", "list", "sift"],
    "give": ["live", "dive", "five", "hive", "drive", "gift", "gave", "glove", "olive", "river"],
    "goodbye": ["goodnight", "goodness", "guidebook", "lullaby", "nearby", "standby", "whereby", "satisfy", "butterfly", "multiply"],
    "grapes": ["shapes", "capes", "drapes", "tapes", "scrapes", "grades", "graves", "grace", "grabs", "grass"],
    "great": ["treat", "street", "greet", "sweet", "wheat", "beat", "heat", "meat", "seat", "grate"],
    "grown": ["brown", "crown", "down", "frown", "gown", "town", "shown", "known", "blown", "thrown"],
    "happy": ["snappy", "clappy", "sappy", "nappy", "yappy", "peppy", "puppy", "hippy", "hobby", "handy"],
    "hard": ["card", "guard", "yard", "heart", "heard", "harm", "harp", "dark", "bark", "park"],
    "have": ["gave", "cave", "save", "wave", "brave", "shave", "half", "heavy", "haven", "hover"],
    "heart": ["art", "cart", "dart", "part", "start", "smart", "chart", "heard", "hard", "heat"],
    "help": ["yelp", "kelp", "held", "helm", "heap", "heal", "hello", "shelf", "self", "felt"],
    "hot": ["dot", "got", "lot", "not", "pot", "rot", "shot", "spot", "hat", "hit"],
    "hungry": ["angry", "country", "laundry", "pantry", "entry", "sentry", "century", "plenty", "twenty", "honey"],
    "important": ["impatient", "immigrant", "impostor", "impression", "improve", "impossible", "imagine", "immediate", "impolite", "ignorant"],
    "island": ["Iceland", "Ireland", "highland", "husband", "instant", "instead", "insect", "inside", "infant", "is land"],
    "jacket": ["basket", "bracket", "blanket", "bucket", "cricket", "pocket", "rocket", "socket", "ticket", "wicked"],
    "jokes": ["pokes", "cokes", "strokes", "broke", "smoke", "spoke", "woke", "choke", "folks", "oaks"],
    "jump": ["bump", "dump", "hump", "lump", "pump", "stump", "trump", "plump", "clump", "slump"],
    "keep": ["deep", "jeep", "peep", "seep", "sleep", "sheep", "steep", "sweep", "beep", "creep"],
    "kept": ["slept", "wept", "crept", "swept", "stepped", "left", "next", "help", "sent", "went"],
    "key": ["bee", "free", "knee", "see", "tea", "tree", "three", "flea", "sea", "pea"],
    "kind": ["find", "mind", "wind", "blind", "grind", "bind", "lined", "dined", "king", "kid"],
    "king": ["ring", "sing", "thing", "bring", "swing", "spring", "string", "wing", "ding", "ping"],
    "kiss": ["miss", "bliss", "this", "hiss", "wish", "dish", "fish", "list", "fist", "wrist"],
    "kite": ["bite", "fight", "light", "might", "night", "right", "sight", "tight", "white", "write"],
    "koala": ["cola", "viola", "gorilla", "vanilla", "umbrella", "banana", "iguana", "llama", "panda", "zebra"],
    "later": ["water", "waiter", "greater", "crater", "skater", "gator", "letter", "ladder", "matter", "better"],
    "laugh": ["half", "calf", "graph", "staff", "leaf", "loaf", "lamp", "last", "love", "lunch"],
    "leaves": ["believes", "sleeves", "heaves", "thieves", "lives", "knives", "waves", "caves", "loaves", "leaders"],
    "lemon": ["melon", "seven", "heaven", "lesson", "lettuce", "level", "lever", "legend", "demon", "lemon"],
    "lesson": ["lemon", "listen", "letter", "lesser", "blossom", "reason", "season", "person", "prison", "mission"],
    "live": ["give", "five", "dive", "hive", "alive", "drive", "thrive", "arrive", "love", "leave"],
    "look": ["book", "cook", "hook", "took", "brook", "shook", "nook", "lock", "luck", "lack"],
    "love": ["dove", "glove", "shove", "above", "move", "prove", "live", "leave", "have", "give"],
    "make": ["bake", "cake", "fake", "lake", "shake", "take", "wake", "brake", "flake", "stake"],
    "many": ["any", "penny", "rainy", "funny", "bunny", "sunny", "honey", "money", "pony", "tiny"],
    "marsupial": ["material", "memorial", "musical", "magical", "tropical", "vertical", "hospital", "festival", "marginal", "principal"],
    "meet": ["feet", "greet", "sheet", "street", "sweet", "treat", "wheat", "beat", "heat", "seat"],
    "mice": ["nice", "rice", "dice", "ice", "price", "slice", "twice", "spice", "vice", "advice"],
    "midday": ["monday", "birthday", "holiday", "today", "someday", "friday", "midway", "subway", "hallway", "doorway"],
    "minute": ["menu", "minus", "mixture", "mitten", "mirror", "middle", "mister", "lettuce", "statue", "tissue"],
    "most": ["post", "toast", "ghost", "host", "coast", "roast", "boast", "lost", "cost", "frost"],
    "mouth": ["south", "youth", "mouse", "house", "couch", "cloud", "mount", "shout", "about", "round"],
    "muscle": ["mussel", "hustle", "bustle", "rustle", "puzzle", "buckle", "muddle", "muzzle", "castle", "missile"],
    "new": ["few", "drew", "flew", "grew", "blew", "knew", "chew", "clue", "glue", "true"],
    "nobody": ["body", "hobby", "lobby", "somebody", "everybody", "anybody", "probably", "nothing", "nodded", "notice"],
    "noisy": ["daisy", "lazy", "crazy", "hazy", "clumsy", "lousy", "messy", "dizzy", "busy", "rosy"],
    "nut": ["but", "cut", "gut", "hut", "put", "shut", "strut", "rut", "mutt", "knot"],
    "oil": ["boil", "coil", "foil", "soil", "toil", "broil", "spoil", "oily", "owl", "old"],
    "our": ["hour", "four", "pour", "sour", "tour", "flour", "power", "tower", "shower", "flower"],
    "paint": ["faint", "saint", "point", "print", "plant", "pint", "pant", "plain", "plate", "pants"],
    "pants": ["plants", "ants", "grants", "chants", "wants", "hands", "bands", "lands", "pens", "paint"],
    "parrot": ["carrot", "pilot", "pirate", "parent", "permit", "pattern", "puppet", "pocket", "planet", "ballot"],
    "people": ["purple", "pebble", "pepper", "pencil", "paddle", "pickle", "puddle", "puzzle", "needle", "steeple"],
    "picnic": ["panic", "plastic", "public", "clinic", "music", "magic", "basic", "fabric", "topic", "comic"],
    "pies": ["ties", "lies", "dies", "flies", "tries", "cries", "fries", "guys", "eyes", "skies"],
    "pillow": ["willow", "yellow", "follow", "hollow", "shallow", "shadow", "window", "elbow", "below", "fellow"],
    "pirate": ["parrot", "private", "pilot", "planet", "parent", "climate", "minute", "senate", "primate", "karate"],
    "place": ["space", "face", "race", "trace", "grace", "pace", "lace", "base", "case", "plate"],
    "plane": ["plan", "plant", "plate", "plain", "blame", "flame", "crane", "brain", "train", "chain"],
    "played": ["stayed", "prayed", "sprayed", "swayed", "delayed", "decayed", "obeyed", "parade", "blade", "grade"],
    "please": ["breeze", "cheese", "freeze", "sneeze", "squeeze", "tease", "peace", "lease", "fleece", "grease"],
    "pretty": ["petty", "plenty", "witty", "gritty", "kitty", "city", "fifty", "penny", "jelly", "berry"],
    "puddle": ["puzzle", "paddle", "middle", "muddle", "cuddle", "huddle", "bubble", "buckle", "bundle", "juggle"],
    "punch": ["bunch", "crunch", "lunch", "munch", "hunch", "brunch", "launch", "ranch", "bench", "pinch"],
    "purple": ["people", "turtle", "puzzle", "simple", "circle", "couple", "puddle", "maple", "apple", "sample"],
    "quiet": ["quite", "quit", "quick", "quilt", "quote", "queen", "quest", "quiz", "riot", "diet"],
    "rain": ["main", "brain", "chain", "drain", "grain", "plain", "train", "pain", "gain", "stain"],
    "ready": ["steady", "already", "heavy", "every", "cherry", "berry", "merry", "jelly", "belly", "really"],
    "reason": ["season", "treason", "lesson", "person", "prison", "poison", "pigeon", "mason", "bison", "beacon"],
    "region": ["reason", "religion", "pigeon", "surgeon", "legend", "lesson", "legion", "station", "section", "version"],
    "rented": ["dented", "vented", "tented", "rested", "tested", "nested", "mended", "bended", "blended", "printed"],
    "rest": ["best", "nest", "test", "west", "chest", "guest", "pest", "quest", "vest", "zest"],
    "right": ["light", "night", "fight", "might", "sight", "tight", "bright", "flight", "knight", "write"],
    "ring": ["king", "sing", "thing", "bring", "swing", "spring", "string", "wing", "ding", "cling"],
    "rough": ["tough", "enough", "stuff", "bluff", "puff", "cuff", "muff", "huff", "buff", "gruff"],
    "said": ["sad", "paid", "laid", "made", "played", "stayed", "maid", "raid", "bed", "red"],
    "salad": ["ballad", "solid", "valid", "pallet", "palace", "balance", "talent", "savage", "salmon", "satin"],
    "save": ["cave", "gave", "wave", "brave", "grave", "shave", "pave", "safe", "same", "sale"],
    "says": ["days", "plays", "stays", "ways", "pays", "raise", "praise", "gaze", "maze", "laze"],
    "scarf": ["star", "scar", "sharp", "shark", "start", "staff", "dwarf", "craft", "draft", "chart"],
    "scary": ["carry", "dairy", "fairy", "hairy", "vary", "cherry", "merry", "berry", "hurry", "worry"],
    "school": ["stool", "pool", "cool", "fool", "tool", "rule", "drool", "spool", "skull", "shall"],
    "seasons": ["reasons", "lessons", "persons", "prisons", "poisons", "gardens", "ribbons", "weapons", "pillows", "regions"],
    "seldom": ["freedom", "kingdom", "wisdom", "random", "selfish", "shelter", "welcome", "problem", "bottom", "system"],
    "shape": ["shake", "shame", "shade", "share", "shave", "grape", "drape", "scrape", "cape", "tape"],
    "share": ["stare", "care", "dare", "fair", "hair", "pair", "rare", "square", "spare", "shape"],
    "shark": ["dark", "bark", "mark", "park", "spark", "sharp", "start", "chart", "heart", "guard"],
    "shelf": ["self", "shell", "help", "health", "wealth", "twelve", "shield", "shift", "shelfed", "chief"],
    "sing": ["ring", "king", "thing", "bring", "swing", "spring", "string", "wing", "cling", "sting"],
    "skirt": ["shirt", "dirt", "squirt", "flirt", "spirit", "short", "sport", "start", "smart", "heart"],
    "slices": ["prices", "spices", "dices", "ices", "vices", "splices", "devices", "advices", "choices", "voices"],
    "smoke": ["spoke", "broke", "joke", "woke", "poke", "stroke", "choke", "cloak", "snake", "shake"],
    "snail": ["trail", "rail", "mail", "tail", "sail", "nail", "fail", "hail", "bail", "pail"],
    "socks": ["rocks", "blocks", "clocks", "docks", "fox", "locks", "knocks", "box", "talks", "walks"],
    "spoon": ["moon", "noon", "soon", "balloon", "cartoon", "monsoon", "raccoon", "cocoon", "baboon", "lagoon"],
    "spring": ["string", "bring", "swing", "ring", "sing", "king", "thing", "fling", "cling", "sting"],
    "star": ["car", "far", "bar", "jar", "guitar", "scar", "tar", "start", "stare", "store"],
    "storm": ["form", "warm", "worm", "norm", "swarm", "charm", "farm", "harm", "alarm", "perform"],
    "student": ["stupid", "stutter", "study", "stumble", "sturdy", "sudden", "subject", "suffer", "suggest", "summit"],
    "subway": ["hallway", "highway", "midway", "doorway", "driveway", "pathway", "runway", "railway", "gateway", "getaway"],
    "summer": ["bummer", "drummer", "hammer", "shimmer", "simmer", "swimmer", "supper", "butter", "rubber", "runner"],
    "sunny": ["funny", "bunny", "honey", "money", "runny", "muddy", "buddy", "puppy", "tummy", "yummy"],
    "supper": ["super", "summer", "suffer", "rubber", "butter", "upper", "copper", "proper", "pepper", "slipper"],
    "sweater": ["weather", "feather", "leather", "heather", "scatter", "chatter", "batter", "matter", "better", "letter"],
    "sweet": ["street", "sheet", "meet", "feet", "greet", "treat", "wheat", "tweet", "fleet", "sleet"],
    "swing": ["ring", "king", "sing", "thing", "bring", "spring", "string", "wing", "fling", "cling"],
    "table": ["cable", "fable", "label", "stable", "able", "maple", "cradle", "candle", "bottle", "trouble"],
    "take care": ["make care", "take dare", "take chair", "bake care", "take fair", "take wear", "fake care", "take share", "take scare", "shake care"],
    "teddy bear": ["teddy bare", "ready bear", "steady bear", "tidy bear", "teddy beer", "teddy gear", "teddy dear", "buddy bear", "muddy bear", "teddy wear"],
    "tell": ["bell", "fell", "sell", "well", "yell", "spell", "smell", "shell", "dwell", "swell"],
    "tent": ["sent", "bent", "dent", "went", "rent", "spent", "meant", "cent", "event", "prevent"],
    "than": ["that", "then", "them", "the", "thin", "van", "man", "can", "fan", "plan"],
    "thank": ["think", "tank", "bank", "blank", "plank", "rank", "sank", "drank", "frank", "crank"],
    "that": ["chat", "flat", "hat", "mat", "bat", "cat", "rat", "sat", "than", "this"],
    "the": ["they", "them", "then", "these", "three", "thee", "there", "their", "she", "he"],
    "their": ["there", "they", "chair", "stair", "pair", "fair", "hair", "bear", "fear", "year"],
    "them": ["then", "than", "the", "gem", "stem", "hem", "ten", "pen", "men", "den"],
    "today": ["yesterday", "someday", "monday", "midday", "holiday", "birthday", "friday", "anyway", "hooray", "array"],
    "top": ["stop", "drop", "hop", "pop", "shop", "chop", "crop", "flop", "mop", "prop"],
    "town": ["down", "brown", "crown", "frown", "gown", "clown", "grown", "drown", "own", "shown"],
    "train": ["rain", "brain", "chain", "drain", "grain", "main", "pain", "plain", "stain", "strain"],
    "travel": ["gravel", "gavel", "novel", "level", "shovel", "trouble", "double", "tunnel", "marvel", "unravel"],
    "trip": ["drip", "grip", "ship", "skip", "clip", "flip", "slip", "strip", "chip", "whip"],
    "uncle": ["ankle", "bundle", "jungle", "fumble", "humble", "mumble", "stumble", "tumble", "buckle", "muscle"],
    "until": ["untie", "unfold", "unless", "under", "undo", "upon", "after", "unfit", "unveil", "unto"],
    "vest": ["best", "rest", "test", "nest", "west", "chest", "guest", "pest", "quest", "zest"],
    "wait": ["weight", "gate", "late", "mate", "plate", "great", "eight", "bait", "fate", "rate"],
    "waiter": ["water", "later", "greater", "crater", "skater", "writer", "winter", "letter", "bitter", "litter"],
    "walk": ["talk", "chalk", "stalk", "wall", "work", "wake", "woke", "wool", "warm", "watch"],
    "want": ["went", "won't", "wasn't", "wand", "wash", "wasp", "what", "rant", "pant", "chant"],
    "water": ["waiter", "later", "matter", "better", "letter", "winter", "sister", "shelter", "weather", "wander"],
    "weekend": ["weekday", "weakened", "weeding", "wedding", "welcome", "wisdom", "western", "weather", "winter", "winding"],
    "went": ["tent", "bent", "dent", "sent", "rent", "spent", "meant", "event", "want", "won't"],
    "when": ["then", "hen", "pen", "ten", "men", "den", "wren", "glen", "where", "what"],
    "win": ["bin", "fin", "pin", "sin", "tin", "thin", "grin", "spin", "twin", "chin"],
    "wing": ["ring", "king", "sing", "thing", "bring", "swing", "spring", "string", "ding", "cling"],
    "winter": ["winner", "dinner", "sister", "mister", "bitter", "litter", "kitten", "mitten", "glitter", "twitter"],
    "young": ["tongue", "lung", "hung", "sung", "among", "along", "belong", "strong", "wrong", "song"]
  };

  /**
   * Get shuffled word choices for a given word.
   * Returns an array of (count + 1) words: `count` distractors + the correct word, shuffled.
   */
  function getChoices(correctWord, count) {
    count = count || 3;
    var distractors = CHOICES[correctWord];
    if (!distractors) return [correctWord];

    // Shuffle distractors
    var shuffled = distractors.slice();
    for (var i = shuffled.length - 1; i > 0; i--) {
      var j = Math.floor(Math.random() * (i + 1));
      var temp = shuffled[i];
      shuffled[i] = shuffled[j];
      shuffled[j] = temp;
    }

    // Pick distractors and add the correct word
    var choices = shuffled.slice(0, count);
    choices.push(correctWord);

    // Shuffle final choices so correct answer is in random position
    for (var i = choices.length - 1; i > 0; i--) {
      var j = Math.floor(Math.random() * (i + 1));
      var temp = choices[i];
      choices[i] = choices[j];
      choices[j] = temp;
    }

    return choices;
  }

  return {
    CHOICES: CHOICES,
    getChoices: getChoices
  };
})();
